with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  GoRestSQL/internal/repository:
    interfaces:
      PaymentRepository:
  GoRestSQL/pkg/kafka:
    interfaces:
      Producer:
