services:
  postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: payment_DB
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: pressly/goose:latest
    depends_on:
      - postgres
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://payment_DB:payment_user@postgres:5432/payment_DB?sslmode=disable
      GOOSE_MIGRATION_DIR: /migrations
    volumes:
      - ./migrations:/migrations
    command:
      - up

  api:
    build: .
    depends_on:
      - postgres
      - migrate
    environment:
      DB_URL: postgres://payment_DB:payment_user@postgres:5432/payment_DB?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  postgres_data: