services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: payment-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: payment-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafdrop: # Kafka Web UI
    image: obsidiandynamics/kafdrop
    container_name: payment-kafdrop
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092" # Connect to Kafka service by name
      JVM_OPTS: "-Xms32M -Xmx64M" # Optional JVM limits
      SERVER_PORT: "9000"

  postgres:
    image: postgres:16
    container_name: payment-postgres
    environment:
      POSTGRES_DB: ${APP_DATABASE__DBNAME}
      POSTGRES_USER: ${APP_DATABASE__USER}
      POSTGRES_PASSWORD: ${APP_DATABASE__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DATABASE__USER} -d ${APP_DATABASE__DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "${APP_SERVER__PORT:-8080}:8080"
    env_file:
      - .env

volumes:
  postgres_data: