// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "GoRestSQL/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) Create(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Create(ctx interface{}, payment interface{}) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(_a0 int64, _a1 error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Payment) (int64, error)) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithOutbox provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) CreateWithOutbox(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOutbox")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_CreateWithOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithOutbox'
type MockPaymentRepository_CreateWithOutbox_Call struct {
	*mock.Call
}

// CreateWithOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) CreateWithOutbox(ctx interface{}, payment interface{}) *MockPaymentRepository_CreateWithOutbox_Call {
	return &MockPaymentRepository_CreateWithOutbox_Call{Call: _e.mock.On("CreateWithOutbox", ctx, payment)}
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) Return(_a0 int64, _a1 error) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) RunAndReturn(run func(context.Context, *model.Payment) (int64, error)) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepository) Delete(ctx context.Context, id int64) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPaymentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPaymentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPaymentRepository_Delete_Call {
	return &MockPaymentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPaymentRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockPaymentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPaymentRepository_Delete_Call) Return(_a0 int64, _a1 error) *MockPaymentRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockPaymentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPayments provides a mock function with given fields: ctx
func (_m *MockPaymentRepository) GetAllPayments(ctx context.Context) ([]model.Payment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayments")
	}

	var r0 []model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Payment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Payment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetAllPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPayments'
type MockPaymentRepository_GetAllPayments_Call struct {
	*mock.Call
}

// GetAllPayments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentRepository_Expecter) GetAllPayments(ctx interface{}) *MockPaymentRepository_GetAllPayments_Call {
	return &MockPaymentRepository_GetAllPayments_Call{Call: _e.mock.On("GetAllPayments", ctx)}
}

func (_c *MockPaymentRepository_GetAllPayments_Call) Run(run func(ctx context.Context)) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentRepository_GetAllPayments_Call) Return(_a0 []model.Payment, _a1 error) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetAllPayments_Call) RunAndReturn(run func(context.Context) ([]model.Payment, error)) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepository) GetById(ctx context.Context, id int64) (*model.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockPaymentRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPaymentRepository_Expecter) GetById(ctx interface{}, id interface{}) *MockPaymentRepository_GetById_Call {
	return &MockPaymentRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockPaymentRepository_GetById_Call) Run(run func(ctx context.Context, id int64)) *MockPaymentRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPaymentRepository_GetById_Call) Return(_a0 *model.Payment, _a1 error) *MockPaymentRepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetById_Call) RunAndReturn(run func(context.Context, int64) (*model.Payment, error)) *MockPaymentRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPerson provides a mock function with given fields: ctx, person
func (_m *MockPaymentRepository) GetByPerson(ctx context.Context, person string) ([]model.Payment, error) {
	ret := _m.Called(ctx, person)

	if len(ret) == 0 {
		panic("no return value specified for GetByPerson")
	}

	var r0 []model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Payment, error)); ok {
		return rf(ctx, person)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Payment); ok {
		r0 = rf(ctx, person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, person)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetByPerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPerson'
type MockPaymentRepository_GetByPerson_Call struct {
	*mock.Call
}

// GetByPerson is a helper method to define mock.On call
//   - ctx context.Context
//   - person string
func (_e *MockPaymentRepository_Expecter) GetByPerson(ctx interface{}, person interface{}) *MockPaymentRepository_GetByPerson_Call {
	return &MockPaymentRepository_GetByPerson_Call{Call: _e.mock.On("GetByPerson", ctx, person)}
}

func (_c *MockPaymentRepository_GetByPerson_Call) Run(run func(ctx context.Context, person string)) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_GetByPerson_Call) Return(_a0 []model.Payment, _a1 error) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetByPerson_Call) RunAndReturn(run func(context.Context, string) ([]model.Payment, error)) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) Update(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPaymentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Update(ctx interface{}, payment interface{}) *MockPaymentRepository_Update_Call {
	return &MockPaymentRepository_Update_Call{Call: _e.mock.On("Update", ctx, payment)}
}

func (_c *MockPaymentRepository_Update_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_Update_Call) Return(_a0 int64, _a1 error) *MockPaymentRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Payment) (int64, error)) *MockPaymentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
