// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"GoRestSQL/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Create(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return returnFunc(ctx, payment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = returnFunc(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Create(ctx any, payment any) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Payment
		if args[1] != nil {
			arg1 = args[1].(*model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(n int64, err error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, payment *model.Payment) (int64, error)) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithOutbox provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) CreateWithOutbox(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOutbox")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return returnFunc(ctx, payment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = returnFunc(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_CreateWithOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithOutbox'
type MockPaymentRepository_CreateWithOutbox_Call struct {
	*mock.Call
}

// CreateWithOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) CreateWithOutbox(ctx any, payment any) *MockPaymentRepository_CreateWithOutbox_Call {
	return &MockPaymentRepository_CreateWithOutbox_Call{Call: _e.mock.On("CreateWithOutbox", ctx, payment)}
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Payment
		if args[1] != nil {
			arg1 = args[1].(*model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) Return(n int64, err error) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPaymentRepository_CreateWithOutbox_Call) RunAndReturn(run func(ctx context.Context, payment *model.Payment) (int64, error)) *MockPaymentRepository_CreateWithOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Delete(ctx context.Context, id int64) (int64, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPaymentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPaymentRepository_Expecter) Delete(ctx any, id any) *MockPaymentRepository_Delete_Call {
	return &MockPaymentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPaymentRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockPaymentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Delete_Call) Return(n int64, err error) *MockPaymentRepository_Delete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPaymentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) (int64, error)) *MockPaymentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPayments provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) GetAllPayments(ctx context.Context) ([]model.Payment, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayments")
	}

	var r0 []model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Payment, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Payment); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_GetAllPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPayments'
type MockPaymentRepository_GetAllPayments_Call struct {
	*mock.Call
}

// GetAllPayments is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentRepository_Expecter) GetAllPayments(ctx any) *MockPaymentRepository_GetAllPayments_Call {
	return &MockPaymentRepository_GetAllPayments_Call{Call: _e.mock.On("GetAllPayments", ctx)}
}

func (_c *MockPaymentRepository_GetAllPayments_Call) Run(run func(ctx context.Context)) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_GetAllPayments_Call) Return(payments []model.Payment, err error) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Return(payments, err)
	return _c
}

func (_c *MockPaymentRepository_GetAllPayments_Call) RunAndReturn(run func(ctx context.Context) ([]model.Payment, error)) *MockPaymentRepository_GetAllPayments_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) GetById(ctx context.Context, id int64) (*model.Payment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Payment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Payment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockPaymentRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockPaymentRepository_Expecter) GetById(ctx any, id any) *MockPaymentRepository_GetById_Call {
	return &MockPaymentRepository_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockPaymentRepository_GetById_Call) Run(run func(ctx context.Context, id int64)) *MockPaymentRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_GetById_Call) Return(payment *model.Payment, err error) *MockPaymentRepository_GetById_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentRepository_GetById_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Payment, error)) *MockPaymentRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPerson provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) GetByPerson(ctx context.Context, person string) ([]model.Payment, error) {
	ret := _mock.Called(ctx, person)

	if len(ret) == 0 {
		panic("no return value specified for GetByPerson")
	}

	var r0 []model.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Payment, error)); ok {
		return returnFunc(ctx, person)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Payment); ok {
		r0 = returnFunc(ctx, person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, person)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_GetByPerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPerson'
type MockPaymentRepository_GetByPerson_Call struct {
	*mock.Call
}

// GetByPerson is a helper method to define mock.On call
//   - ctx context.Context
//   - person string
func (_e *MockPaymentRepository_Expecter) GetByPerson(ctx any, person any) *MockPaymentRepository_GetByPerson_Call {
	return &MockPaymentRepository_GetByPerson_Call{Call: _e.mock.On("GetByPerson", ctx, person)}
}

func (_c *MockPaymentRepository_GetByPerson_Call) Run(run func(ctx context.Context, person string)) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_GetByPerson_Call) Return(payments []model.Payment, err error) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Return(payments, err)
	return _c
}

func (_c *MockPaymentRepository_GetByPerson_Call) RunAndReturn(run func(ctx context.Context, person string) ([]model.Payment, error)) *MockPaymentRepository_GetByPerson_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Update(ctx context.Context, payment *model.Payment) (int64, error) {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) (int64, error)); ok {
		return returnFunc(ctx, payment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Payment) int64); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Payment) error); ok {
		r1 = returnFunc(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPaymentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Update(ctx any, payment any) *MockPaymentRepository_Update_Call {
	return &MockPaymentRepository_Update_Call{Call: _e.mock.On("Update", ctx, payment)}
}

func (_c *MockPaymentRepository_Update_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Payment
		if args[1] != nil {
			arg1 = args[1].(*model.Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Update_Call) Return(n int64, err error) *MockPaymentRepository_Update_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPaymentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, payment *model.Payment) (int64, error)) *MockPaymentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
