// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	kafka "GoRestSQL/pkg/kafka"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockProducer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockProducer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockProducer_Expecter) Close() *MockProducer_Close_Call {
	return &MockProducer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockProducer_Close_Call) Run(run func()) *MockProducer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProducer_Close_Call) Return(_a0 error) *MockProducer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_Close_Call) RunAndReturn(run func() error) *MockProducer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, msg
func (_m *MockProducer) SendMessage(ctx context.Context, msg kafka.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kafka.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockProducer_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg kafka.Message
func (_e *MockProducer_Expecter) SendMessage(ctx interface{}, msg interface{}) *MockProducer_SendMessage_Call {
	return &MockProducer_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, msg)}
}

func (_c *MockProducer_SendMessage_Call) Run(run func(ctx context.Context, msg kafka.Message)) *MockProducer_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kafka.Message))
	})
	return _c
}

func (_c *MockProducer_SendMessage_Call) Return(_a0 error) *MockProducer_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_SendMessage_Call) RunAndReturn(run func(context.Context, kafka.Message) error) *MockProducer_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
